name: Android CI TEST


#Takes input branch,url and build variant
on: 
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Choose one of the build_variant.(1)envPRE_PRODDebug(2)envTESTDebug(3)envQADebug(4)envPRODDebug'     
        required: true
        default: envTESTDebug
      branch:
        description: 'which branch'
        required: true
      url:
        description: 'which url should the apk point to(Only to be filled in case of test build) eg-https://rpc.semaai.com'
        required: false

#Specify the job and its properties
jobs:
  build:

    runs-on: ubuntu-latest

#specify the env variables

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

#Select the branch
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.inputs.branch}}

#Replace the url pointing to the env
    - name: Replace the test env url
      run: sed -i "s#{{url_test}}#\${{ github.event.inputs.url }}#" /home/runner/work/field-staff-app/field-staff-app/gradle.properties

    - name: cat the file to validate url
      run: cat /home/runner/work/field-staff-app/field-staff-app/gradle.properties

#Setup jdk version

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle



    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # - name: dir1
    #   run: ls buildSrc


    - name: dir2
      run: pwd   


    - name: dir3
      run: sudo apt install tree;tree apk;tree /apk;tree . 


#Start the build process
    - name: Build with Gradle
      run: ./gradlew assemble${{ github.event.inputs.build_variant}}




#upload the artifact
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: /home/runner/work/field-staff-app/field-staff-app/app/build/outputs


    - name: dir0
      run: tree .

    - name: dir1
      run: tree  /home/runner/work/field-staff-app/field-staff-app/buildSrc


    - name: dir2
      run: tree  /home/runner/work/field-staff-app/field-staff-app/

    - name: dir3
      run: tree  /home/runner/work/field-staff-app/field-staff-app/app


    - name: dir4
      run: tree  /home/runner/work/field-staff-app/field-staff-app/gradle   
    
    - name: dir5
      run: tree  /home/runner/work/field-staff-app/field-staff-app/build  
